version: '3.8'

services:
  # nest api
  nest-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - PORT=${PORT}
      - ACCESS_SECRET_KEY=${ACCESS_SECRET_KEY}
      - REFRESH_SECRET_KEY=${REFRESH_SECRET_KEY}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_ADMIN_EMAIL=${DB_ADMIN_EMAIL}
      - DB_ADMIN_PASSWORD=${DB_ADMIN_PASSWORD}
    volumes:
      - ./src:/usr/src/app/src
    command: npm run start:dev
    depends_on:
      - postgres

  # postgreSQL database
  postgres:
    image: postgres:13
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # postgreSQL admin 
  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - postgres
    ports:
      - "85:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${DB_ADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${DB_ADMIN_PASSWORD}
    restart: unless-stopped

  # kong database
  kong-database:
    image: postgres:13
    container_name: kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    ports:
      - '5433:5432'
    volumes:
      - kong_db_data:/var/lib/postgresql/data

  # kong migrations
  kong-migrations:
    image: kong:3.0
    container_name: kong-migrations
    command: kong migrations bootstrap
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
      KONG_CASSANDRA_CONTACT_POINTS: kong-database

  # kong gateway
  kong:
    image: kong:3.0
    container_name: kong
    depends_on:
      - kong-database
      - kong-migrations
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - '8000:8000'
      - '8443:8443'
      - '8001:8001'
      - '8444:8444'
    restart: always

  # konga dashboard
  konga:
    image: pantsel/konga:latest
    container_name: konga
    environment:
      DB_ADAPTER: postgres
      DB_HOST: kong-database
      DB_PORT: 5432
      DB_USER: kong
      DB_PASSWORD: kong
      DB_DATABASE: kong
    ports:
      - '1337:1337'
    depends_on:
      - kong-database

volumes:
  postgres_data:
  kong_db_data: